apiVersion: ENC[AES256_GCM,data:aQo=,iv:NigPAeIJ/o1YpFv7Du451Wk21k88JJqJAV3kyjyjEJ8=,tag:BTMhUn3d7fh4QPFqjHjTtA==,type:str]
kind: ENC[AES256_GCM,data:30+iQbtU,iv:4tyjiPXCgqxbcxxgpYIJbLAgegsL9lvXwpz6UbBRx64=,tag:1TVnsuvZ9WkPPkeaOHtHyA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TRynu5wxZpy68d1anMaj,iv:inMPWwzPkJyM7PUvyZIyA5cSqPiml52JJgnWApSGKOU=,tag:8OK6zoistrlVapmIe7u4KQ==,type:str]
    namespace: ENC[AES256_GCM,data:PeeqSNZS8g==,iv:jdpwiOMtNzibKiBZWc4qAlI/rq31JddEgOGzog/eMZs=,tag:QALjzRh35k/U9oY0JPk8Mw==,type:str]
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:uzDPAkgfmnySVI0RuSn0T1dNpeYX+i+PMn6Da4W2g4iiGYKKaZbgJw==,iv:r0g3mfnXXjvbg7YHyCcZ6yo/omL5ZiQc/Qc6YnTXm6c=,tag:D1qk1axaRA1oiAyb7fucYA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:6pLYq6uu+8M8gLqiQPuWvlbpif4y37Mc9juBBL/qfgo1DJRArTW5CU7aAO/SaivdrsPlO2pm0TiAmQfR+joMEJk8QQQDqlaUSJIYoAed4W5OiLxVYBmGokcEbLLyKvzl1MMGu/DHkDAEMkKiWksyII1iwBnlw4HSmM12j6gdwv0=,iv:sSn0p+REeA522wnLu6xIZX3dnbOQpy3sGfb2uTZnvrY=,tag:73mAcNsorKVP5/b49FZAIQ==,type:str]
    admin-user: ENC[AES256_GCM,data:RcJbQiM=,iv:5YIT1BDxfZDqINGiq7RUsbBKIO+QmauusYXfBlujkuE=,tag:m5PUyuiN7Wrpma/8SdH2gQ==,type:str]
    admin-password: ENC[AES256_GCM,data:LzlRi5Qn1aMEfuB2GwcHo5/jOaE=,iv:CKyfBUWxo9svRLgkR/Gkin41chWK6ZNwCL+FlzZ4i6E=,tag:j27YN+fsPyHoK/hZJgXVDg==,type:str]
sops:
    age:
        - recipient: age1llr97g06zt0mmn8uv6dv2kt9lu88wxcl2saxsp8g3z2hsdx4uqzqlttrng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRGViUXpzYlM3dmRLa0lP
            MERmU29PaTc5bnNydVZhaVk4L0luVVZrejIwCmJwaU1RSkd1alhCbkM0ZEZlRVg0
            ODhHempUczluVFJHTDhTU3JVOGMvZzAKLS0tIDhRQlFlejZhWElqU2xZanJwNmVQ
            VlZRNzZ5RnFzNDlsRk5xM0JoTXpPMncKRp/1a0ktPUgsr6gzZ2r3SHI9LmQbiAbH
            8EzuK9WOPkau3u14AI+d4LOY7x01o6LusOILy8jVm0M8x1kz034Kkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T09:55:53Z"
    mac: ENC[AES256_GCM,data:HgDgCjOc/wHAgQfE5d3WdEK/RHK3An/Vi7lJHERll0RpSaa48UFYhE3q2W3qC62rYghOVZAU2ZwZV0MHbAuPRf5FhSRc4FMBV/y8IzhXDRdMWPI3tcwxzqaJ+eEHgES/yZEyUcDQUf1jtlrzxFSVLHyUJ6GxLu4vYe7dbb4Nqio=,iv:yEujMLVPgo8b3DXgD+4D81DGzSOgryGqGVXLgz3Lr+c=,tag:1W5uHXXYOE+XrFwnF5mA3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
