apiVersion: apps/v1
kind: Deployment
metadata:
  name: mao-bot
  labels:
    app: mao-bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mao-bot
  template:
    metadata:
      labels:
        app: mao-bot
    spec:
      containers:
        - name: mao-bot
          image: ghcr.io/maooz4426/mao-bot
          envFrom:
            - secretRef:
                name: mao-bot-secrets
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

