apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mao-bot
resources:
  - deployment.yaml
generators:
  - secret-generator.yaml
images:
  - name: ghcr.io/maooz4426/mao-bot
    newTag: sha-8c3e970
