apiVersion: ENC[AES256_GCM,data:lpI=,iv:12X2PJP1tMFL9TN1jIZSeAW3BT/0V+PHK1vc2z6c+FU=,tag:U8P+KctEyE2QY9T50KsO6Q==,type:str]
kind: ENC[AES256_GCM,data:oCw7XUK4,iv:u+rd8yyatoFs+czTZs2MJezuUomU0tTDV439dI0f0yA=,tag:p9Hf3U0pbelYI8+GmIeoxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:woe2xkUnOxk8NGWUMMoH,iv:Ycldd+XR1DwIMx42PXbZxr1hkEztESDdksI2sYTSSls=,tag:SL7/ec1Bqk6MlVlQSas/Yw==,type:str]
    namespace: ENC[AES256_GCM,data:6Bwhb7poIA==,iv:Kk40u7iAmisdbNaiZL+Pzth9cn32j35VuNuu3jj/GlU=,tag:BGMDVff/3ewie/GFNZawUA==,type:str]
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:q9P6uvszhKXrE+vdFiJCF2iGzbjDmQNWdM907jRUumDzl/sr9m13YA==,iv:qsXjanOtNpkZXYcmz7bA+nMos8/LzNPj1kpsXygfBm8=,tag:ZwlYkdw3H7Uuwee4fsCdFw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ckyTrymTL5zrDmWguyF5cbnF4mPInMDTvsNOT5hwixQ17Dqy7rOWUXmSKtza6622RYMhIo8/65c02tg7oCBMA1wZO4kVVWFjd3GJbEldbUqddHz/CpDXsIt2o9YYP+K+tykZ7Rkec6P4ZFudnbb70VY4UB5IbyRduPz3u8GRDsU=,iv:lncLU4oVg/jA5mcFxA7XyrnyyFjG8PDWDCGNALg7PoU=,tag:9r43uIDy4bIkQ3ywNT1k4A==,type:str]
sops:
    age:
        - recipient: age1llr97g06zt0mmn8uv6dv2kt9lu88wxcl2saxsp8g3z2hsdx4uqzqlttrng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRDdUcHB2VnJ6N1M1aFhV
            Znc3YVZTSEVEUSttUVFxQVp6YjBoWVFLaHhJCmRqTnNxcDRxUVg3RlRMUzl3a3cx
            TWRzYlh5bUxqVkpqVC9zcHBwdEFRcWsKLS0tIGM4bHUzdEl6WTA0ZHp4d2dSdEFm
            VEhXbU1jZ2hKZFNzR0p2MkdUV1NZRlEKB91SkNMdeKDj1BoI7pdXLTm0q4bdbu2Y
            MdZCl3XMaRldUWDN0fJM8jVQ2Hsyl4FssaMSq8cZ6xrZOLkE26IOwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T06:59:52Z"
    mac: ENC[AES256_GCM,data:IHdNKfEKeIVOQS76iMc+XDN+ZjfBzUQckg6Oj5sV/nzuz/LyZhgU3XGK/Q/nbNl9MDutJezg3/O+NjkJxVB2xnVuV+ukypAeGKiirDPupdPCYPHf1b3f7Hip0X/wmnkwAbwabgkjC4OmugSYP3Wa7MgECusuejHSGk9nn8s52vE=,iv:BdfMGfTjS6g/yczX66p+uv/+uq4j9jC4y9INqbyOFGE=,tag:gnQ2bjvrb1mnea24kTxd/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
