apiVersion: ENC[AES256_GCM,data:nKE=,iv:8U5PJthRG/qRNu21OTs4PppeQRXbls6uH7VYRoii250=,tag:H2x//CcEG2wfl788U6KMmQ==,type:str]
kind: ENC[AES256_GCM,data:HrO0WCYq,iv:XG2VnGxkzQK4ucyjs6lSIPFYmpk0V/6RnE5RER5o/eA=,tag:q9bph/pd/f7aBQTQ4PrtKw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bq+pVpXQazBOQSao+qqa,iv:1mIFVhCkoxOSYlG+Wr48oWWgIUz7kDD4cG1j9zp8jfc=,tag:Vq2oBmoGkkINYllyCjCi3A==,type:str]
    namespace: ENC[AES256_GCM,data:iqOliK6I1A==,iv:XNKvYU+Vbw6jL2KVkaiT1ebmlBXIo/h50wl9yUwn9/Y=,tag:xPxUGq/TNvnMrLwSu+RD3A==,type:str]
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:giHhrUNrVrlwY1D3HxlvSf14ZpEoNonis8YO8FAoV4S0Yp+2c1nzag==,iv:SYdfgYVnDQS0uD/tLvmjzsd2BTRynNY7iNQA0miBWwE=,tag:Fj+zP/JPMYGFMMPMtlBdUA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:i4crvf9W1Cjwr9qfRVpDuwhL+UEW4Q7MEAxFKtg9PRHl8ICbPAkqvKQ3ZkOPAN3PciFUjFhvOgQFhLbG3XGUik0DcjeSRaONopBIPPGi7L2QyrBPkQXZHTzyk+7Ag9RGtD8t6bOjSx/GU8jx9uJn2k/+RxM9cP/pB0FhenfTeVw=,iv:GZmC7ukQqaSKrxqnvhM0iZNnaEQSWu2jIsGSdD/baAs=,tag:9yVyc4Y8K1otStFXfJx5Qw==,type:str]
sops:
    age:
        - recipient: age1llr97g06zt0mmn8uv6dv2kt9lu88wxcl2saxsp8g3z2hsdx4uqzqlttrng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU1RTRkh0NkRJNDdieVNH
            M1lBNFkzd0FrbDhiZURjNDN6N0tab1lhSW1jCjdvNVYrVWJFa1p4cXExZFhhRmdv
            U3NIcGpoSTVMOG03ZUMvWGhmd1lWaHMKLS0tIG9EaWk2dENnUTE5RnJicVdOQUhJ
            cFNOeEtRRWZmZVd6K1cyeVZhTUY3aHcKpnVjppP8Jb1gYJk0VSKQRpwb7K7i5VAG
            1HxFlmVSWpvKbAbCe/1NFkT/6jeR4irshH0hBOsOlOp55oTP88Kqsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T07:24:55Z"
    mac: ENC[AES256_GCM,data:qrSD++rHJXgTJZwz1SOVfooVvJkQhmwri4MTBO35HAtdcgEaU5GCoQ9FVG3HW6zhKLdmhacjWmXvoGcRE17nj+xC/Hnausk2p8Kh0b4mAG2dfB0LBuY1ueHyGmnpk2uIaD5QhsaZziiDMMy+5MK28VPq9koGd58Efsa0JdFIlIs=,iv:o7VRvfXbw+1ETuyp6/YrAAClQfGChmCg9LKY+MnI0D0=,tag:GMwuiCvf9FcOo4zqARrMyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
