apiVersion: ENC[AES256_GCM,data:32E=,iv:t0gipVfwF/Mt+JiAvRwSiao0RMrAzMvlHV8S/l3U1Kg=,tag:0iR/PdpcL2Tr08gjCzw+hA==,type:str]
kind: ENC[AES256_GCM,data:g4BNGncs,iv:4q8PG6uiACYFEh/490KON0C20vFS6ZGXJ8Ntk5H9Das=,tag:7bhvzN5fza+vCJDCjhy9Kw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S6zlV1nlA+ri8bxFvFQh,iv:JAUxvr5z0YQSkWnlHqAHXhRWg/wrT6kxC9SpjzgCsZo=,tag:2KHVPkIPewjvR+zCb+FPoA==,type:str]
    namespace: ENC[AES256_GCM,data:4yn4ef+Zow==,iv:tVlnr79XE+3gdVR88d76bF2Mq5KofSgfnQ8nkqThY0s=,tag:PFlx4gCKPE9usLYz72zw2Q==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:8eVAVLjeGmFa91QctdjyM8eunZg09CDCswUQeZ+ucYvWK5249v7qnBHWF6HIFDl7XP3Q7MIdeLjRoY0r1+Tyxn41T1kuJiQp,iv:3qbMJdTjF3DkJb2Bog7s4Wv9SWvGeBHv3Cws/I1aptA=,tag:1C8wjutqoYJK5yao5Z+kbQ==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:fZLs8bsPJuywVC8WaO6CXezZOw==,iv:A3I4jkeRA8Kstkz3JTSC+7ri/EoVPk+ZE6q489yHig0=,tag:2j3piB1ishz+0YsGSBrLNg==,type:str]
sops:
    age:
        - recipient: age1llr97g06zt0mmn8uv6dv2kt9lu88wxcl2saxsp8g3z2hsdx4uqzqlttrng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWm11ejdnQnlxU2YwSG85
            azFrWGxZb0dIRUZodVQ5NFN6Q2hoUlkyU2lNCmlIbHdZditzSTFGOENhQWNUaGhC
            UFZwNmdJcnVBZ2hBSzZRd2l2WVN2Qm8KLS0tIEp6Ni9XTGtKdC9BNWNVUkZhbU1P
            Z3A5RFRCUDhzcVhLekpFUkoySHp6bkUKnaQJlbXroe06tto5EYLqkMSIyaS6ptC1
            cFILP2yJnkBqUpZpmKB2dLm0MN6IFr6GdBCBm9WY/ZlSwJMjaanMEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T15:44:28Z"
    mac: ENC[AES256_GCM,data:/LESpxBKHbPNT9eK3A/fCWi4ZcSvye5UOuTOVFbsvTPxqtDQjs4/jwgRUdEoBqQqXN1duqdLYtGjfPfXZm7ec924MddAjvFiUFuSAOQqdLMWzSMnG1Gx8gnSIxIeYbBelbNR1TwC0IPuDCjO2HJC9CzYe4k9uhshhXHzArowmPE=,iv:HaHf9t5DhX3wXPBqZgY/2b2PrZPY5ccbP1KyuTotk8w=,tag:39phlUideDnYDpBZP4cZqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
