apiVersion: ENC[AES256_GCM,data:P7g=,iv:hUhoFpUO3Fy74bv0b4TxrH3hblir9Pva/04x/VtSexc=,tag:PbVN4Dx5O4NpbLE1bi9Peg==,type:str]
kind: ENC[AES256_GCM,data:okvXF/SO,iv:jdqLvbbkjkyw96/n+AVW2A+1tiBoIhWS4bG0Hn2eTI8=,tag:DUmn1DSgEJ/Fr9pbYed4MA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SeQvRngVyG9YK5PAyERX,iv:PCufZN6Cwt5jfj6HtlC06Pa5SrHBuo9bS2Pu8CjAoaM=,tag:83FVHTu0g3U3FiPB0BMQIw==,type:str]
    namespace: ENC[AES256_GCM,data:P9zSudYpCA==,iv:iudvusG0cUnDfO1y6hZ4rPndZZz+yPn53XqEndlbBHU=,tag:RP8n8aAIq4kL61ObBakghg==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:N8/yW3wXH3TrGd6ZhCna0N1JrI3+cIKTBv3hfSYNLIZqmbn3Um0l4jFxwz3pV0wDcU0bl0PgxmZyo7GVvFUPg4H+AQ8HNAPU,iv:66CStXO1jbh+u7X5pDQ/sbzTZMo9DsW9zvVcTasaY60=,tag:dIz1IcZ2OoOjuYUtcIa1yA==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:8D3mwi79naH1VLHb7kEdwemw3w==,iv:mjUhkTITT1Ti1vRvOcpEArEfoXaqHmLKcXWmbwuc8Sw=,tag:/xp7X8+vGL+WdR5oHRtBMg==,type:int]
sops:
    age:
        - recipient: age1llr97g06zt0mmn8uv6dv2kt9lu88wxcl2saxsp8g3z2hsdx4uqzqlttrng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbFhTb00vYitFZlpJQ3ZG
            ZzZTZXJxVHYxRWlZOW1PckRubzNJMnBuazAwCkpMZEZsMlBkR2QvQnhrYjFKbDRQ
            OHArWEpPdGVMaDNVZGdka3QvcEZkMUEKLS0tIEJ3ekdQZDBCTHJIMFgyb1YrV0hy
            dFdKQkQ5NGRHVkxXTU03N1hPblpHNG8Kb2OylaNOv+7f25xFGBDmDbA7Jp2N4DrY
            0uCx8LGfDLs1QTsux3dmZgjJ6ibuk6ort+CWonLUi5t5NTYXwn27vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T15:08:54Z"
    mac: ENC[AES256_GCM,data:3fkv26+2CRu7W1I0b9to7Ww9yQyRqstLUukwNj6wFzES2bvX8KFJaAjcNZf3KsaoShk8t6EbFDf2ZQNL91X29r5GNxKfwOsyFxr/s9OxQ1MQWxwgYNOM7+KCJEmPZ+gaDzieCD/KiZbKcVSbJBFb7tCCNtNrumOkHsxds1EMudk=,iv:PY8IPAtRZSD6gMmooqwsbllu9YcFj/1ghRx/YgvqVoc=,tag:cUt9Ihh9c0bgwPvMBxqFfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
