apiVersion: ENC[AES256_GCM,data:hcM=,iv:QbDsRMWrRA7HXuPU/m8jZd5YrmA66N3FtlJXaA55GOY=,tag:0EO7+PGwJ4hPi4zSnmCO8A==,type:str]
kind: ENC[AES256_GCM,data:NrGN7mK4,iv:cdFcUNjDZZK4YobFPWSGI7CsSDd8omsnWmnq391T8QU=,tag:9soL7DhFUXcIz/3FAr38TQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5qjJeyzMuQ2fPUDO1WI=,iv:m6nujqJCYAnmup5yJNvVcmG9nxmuqa+qoCn8O3Q1/pA=,tag:WNBnH+944zACE2MnB4ztrw==,type:str]
    namespace: ENC[AES256_GCM,data:O/WPO0lPJl1k,iv:nSvG/gkojh4l+uxe1VDGqFfMffGmsgeEZN82VCcJ8EU=,tag:8D+8X8V/WFi+b5NF1usYBg==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:zEUV1HmSz0i/Z48PBwaI0zQ=,iv:bwEvO3isqjoKMVGot9SKj0NQ7mOXxqNsYBCpcjSRpfc=,tag:AQeyJm1tsUiF9Fk4VuFfyw==,type:str]
    client_secret: ENC[AES256_GCM,data:4VhJVfbK0LNmg/iE8gNdEZ0Q08Rm3naVz0we22JAxD0sPTEZIqyNOpVTsQuYY9NlZuL7G2fXuDM7Wv6CbP2T+Q==,iv:0DfJdEZoFfIBtMDO/gccW35dMoRxqRFzQ8bXggBJLlc=,tag:hF1zuTVt7vPA1SANKF8YFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaWJMdDR6cUdXUWViNkxK
            enBVZ0xZSTFvZzZZc3lXdCtsUUVpRDR5U0ZrCjVLcWVRQkp6NXZac3NZUEppenMz
            Yi9qK2szclVIdERQeHppMmtOK0wzRkkKLS0tIGxrVi92VjFUb244QmZWWU1Leldr
            NU5DNTl0Z01pNG9TQjQycGtHQ21STVkKJeLsv+WOdvJTYdnCuLlgaLXEPIufxaEB
            zuFZyIwUSjEEJ1Jcaoy4x8II8POhUOQ3gnAulYVylWJfsXATmDyh/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1llr97g06zt0mmn8uv6dv2kt9lu88wxcl2saxsp8g3z2hsdx4uqzqlttrng
    lastmodified: "2026-09-09T17:37:20Z"
    mac: ENC[AES256_GCM,data:m4rTHTmLaNRvRg/l2/RXjLVYod9On41ZxEWI9MT924bGkLCtnywrfEob3CauV0rDQL4AlDAuKY3U3JAH0fkd70W7TlEn+WeBObaWOnfurplrqB8d5w/ID8aOo9gsTHL1ryHqaJmlMMGG6G0g7EpI6SYIV8P6xEKc00DBwtlqjSE=,iv:G2pF6VUM+SZb9kfiX/sSMqdY2gxrzzhnSWyulV8dL90=,tag:IhRYGcGIpuqptYTeq0xjOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
