apiVersion: v1
kind: Service
metadata:
  name: treafik-tailscale-service
  namespace: kube-system
  annotations:
    tailscale.com/hostname: k3s-master-01-traefik
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-kube-system
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: websecure
      port: 443
      targetPort: websecure

