apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - image-updater.yaml
generators:
  - secret-generator.yaml
helmCharts:
  - name: argocd-image-updater
    repo: https://argoproj.github.io/argo-helm
    version: 1.2.4
    releaseName: argocd-image-updater
    namespace: argocd
    valuesFile: values.yaml
