admin:
  existingSecret: grafana-secrets
  userKey: admin-user
  passwordKey: admin-password
deploymentStrategy:
  type: Recreate
persistence:
  enabled: true
  size: 2Gi
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
service:
  type: ClusterIP
  port: 80
envFromSecret: grafana-secrets
grafana.ini:
  server:
    root_url: https://grafana.maooz4426.com
  auth.generic_oauth:
    enabled: true
    name: Authentik
    allow_sign_up: true
    scopes: "openid email profile"
    auth_url: https://auth.maooz4426.com/application/o/authorize/
    token_url: https://auth.maooz4426.com/application/o/token/
    api_url: https://auth.maooz4426.com/application/o/userinfo/
    role_attribute_path: "'Admin'"
    auto_login: false
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: "Prometheus"
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    node-exporter:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/1860/revisions/32/download

