authentik:
  log_level: info
  existingSecret:
    secretName: authentik-secret
global:
  envFrom:
    - secretRef:
        name: authentik-secret
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: authentik-postgresql
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__USER
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"
postgresql:
  enabled: true
  auth:
    existingSecret: authentik-secret
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
server:
  replicas: 1
  ingress:
    enabled: false
worker:
  replicas: 1
