apiVersion: ENC[AES256_GCM,data:3rA=,iv:kJPqnyrePbVyW2vsw3I5Mlw/upgAcSmOIQL93Y9xRIo=,tag:2TbiTJLVkpngK8PpRJ0Cdg==,type:str]
kind: ENC[AES256_GCM,data:QUSJ58IW,iv:sdvFcyNjp25VDdg2AUxwguM3bG+ROARb3cYDYBbw44o=,tag:ytOCkapXvKnSjYv8VnFJgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8Oui/5rNoimwowDeTr9C7g==,iv:8A5GWeaj++1a31OMNZrHxEYjQGOl3/3ixZq46MsyESw=,tag:GunezFOhkdzwHxrQvLOi/A==,type:str]
    namespace: ENC[AES256_GCM,data:jr6kq/KkAsvU,iv:AodGXs5Kj2xh4U8oMor2rko2XNqt5d7XnZ1vH/c0vZM=,tag:NLudPEQvdv0Lej9M1duhrQ==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:o0J8Mwz2+lgZ6nES5XdnjxI9O5eUDA1jW3dhQMNN3TmHT1eo3kYsdxbbjWgnvYQyRdDsf9v/YoPB1zHW/ZlBSvdcLeSfejOclpPsaLtwkBM=,iv:pfReX0V+Mm1+bOChYQ8AsSpnsCKQKOSt4xCJFo/HkOU=,tag:Be8iY+D5HVXNzqq356CoJg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:MNgYAgpFUkmCWRcynPx7ERE3Mbknux7BPwNOwW+XSk76XbzXdnl/AQZ8FDTgVyHD,iv:303IiQJCR+CU8RbykWkZoY2D6oMEGd0k/Q7mhibdNfA=,tag:SeSyCLRKvxxPFGWZkW8NIA==,type:str]
    password: ENC[AES256_GCM,data:xuNvUqjMAZNGL3yc9DIPRDiStOi4viLw3+iDTrZZdAnvVGck9IAXv4mMPAcRod7w,iv:YFAqXHGWyTfwF/aLlupuLK7v+gQ72DKlQA05RHvitxM=,tag:uiD5YWyH6HIh/5tmxrHPJQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:vOfLEIf9b7nzpkL6/SiXhlZQ+I2RXXutEwjL/4fqFbVGWmTlcqKCcufrkbfsBX6i,iv:zaGqEkx7uE0aDEsYafNFAO5RcJ5P7v/NQucisSAS96I=,tag:GLeNCVAuL3yN5eUtPZEkpw==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:1Mh+Dif0HzAMnRPG/HpMsPqn7eJQNV92tR6sK7ssIXA=,iv:PC13HcezYBXVDDehg7SlAj+ggIBhL6z1vxfD8HNIdpA=,tag:djlCfYML2pnG4XYhLpu+Hg==,type:str]
sops:
    age:
        - recipient: age1llr97g06zt0mmn8uv6dv2kt9lu88wxcl2saxsp8g3z2hsdx4uqzqlttrng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcjNEY1Z5UVE4UStxeUxN
            MnhIVVBoNEJNbmNINGtXa0p0aWpNb0tlbWpzCmE2WGg4ZFo5M1FzN3kvTTEzalVT
            UllOQmw2UHhEUFF4Vy9EaUJONG43d3MKLS0tIGlVYy9xWkp0c2ZFNUdyWWVJYWpl
            WXFWOHRmZFY4MkxMbUJtMTNjaHJNMEEKwSbg/9K7SaJs3WlJ4KcZ+yYIVO42tZuf
            jMVZl1g4NMnvMcAFAObPoxW4d6Pe/n4Rbec2/262W9Qao0Fy2vuclw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T15:43:14Z"
    mac: ENC[AES256_GCM,data:xeIEmHx89tWZJbjenb2BtzQuuHZfxA7BN/8lLRRlQuErTpw6PG7oCv6T8k39mYAJou5CH1csd43E+DqboGip75NCL7xZkc2b38RlmWZm+0EqbI6T2gYCxgK4EhI47/U7sxKyPCKohkQluazP4YIHq3htvgvBJ4TMT5EpE6WfxO0=,iv:mkVner6fWAqpPzxt6JmYGYXhWwquT4BwgG48QhGouJE=,tag:9xxAnGJX9jDwHTc1wiUB6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
