apiVersion: ENC[AES256_GCM,data:dvs=,iv:StN46xf2ANC8LlHGhnAEN7L9su6PouWptxzK4uI623o=,tag:0WVVzD/RKoyUxSZJhXgPSQ==,type:str]
kind: ENC[AES256_GCM,data:DVyihbfi,iv:a5FD3PfTIHOUpJaMEDRCDU/3eXMJnn7U24sGLIVmPrg=,tag:NAslX382v7SBB2pJnC3SJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hMXhblNs9DLIvAneLYMbe2m1oxJNHlY=,iv:wIkUEoIIKhgT1Kg2YJprMk8bo5j97rJ9nO5SJ8umGFU=,tag:froPbZxlbZ1WPP9vFtcyzg==,type:str]
    namespace: ENC[AES256_GCM,data:k9S0iE4Kw2vdNyc=,iv:qGZU8e9o7cVD6nXuIyzq259nLNjtZCgPNOGOtJb5DMg=,tag:SN3xKz8O3htmWxp0wiaH2g==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:6Es4UKxP0iFgK7MN0e9Z4LY4nn0+tHsPzPmBjeoOA74E2g5N6a4XhKhW3VAyYTQZf+Nj96f81QreUmLvJYhS1uku7c1idtewWBbvBQRbaBVEEU9iA1k8EOu/3V1oCeyoHGvRaO54Y7eywsNZ8qQZ9aO9AcE03iw8nalgjWw1X4iIWtrSgYRvMj2EEU6HY+qPxtyMUkHDr+QAh8IaynqehbZ2+uAWnQBXHGjD7Nptmg==,iv:onrYzZW1MuuQ1bO4IQxMF/IoIht3OX0bZlQ0IioK50c=,tag:d9DCDgoLk9T5OjJzl5F2Dg==,type:str]
sops:
    age:
        - recipient: age1llr97g06zt0mmn8uv6dv2kt9lu88wxcl2saxsp8g3z2hsdx4uqzqlttrng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MndjYk9EdEZINHBzNytS
            UXhyYUY4NCtlOEVvTnd2dXpqT1VrS0FMZDNzCnFTdlFNblZ3VEpyU0t2NXR4aWVw
            SXBzUDFXd2o2UlRjbmcrMTNTUW4ycjgKLS0tIGtWWDZ6Sk5qMGpuM0JkMWdhNmFo
            VVFYRU5NUWxWOElOWXJzNTlyeU1la3MKz3KWuD6guSfziWAaURHflbd1L4rXwajN
            B+MTM37/xMnHrCBOw9n37DGihpjkhs3CGhwueKsKBBU2fFQeSHHQRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T04:59:58Z"
    mac: ENC[AES256_GCM,data:BPxFaEHHEzuvwRV5pMt77VW55vSVMjq4RoKddVt5cALP27T8S9n4Su25oj/W/t16JtGwbjcRjtR+tDVjJeELXmS/1MIpcbJCOyLgxt+caaU7rQxehjyxla8GpFrnwiBFCQS0dINcpBjVs0VJJh4jSzq2njJkY3sBDRT2EWBMDVc=,iv:CqnIS+LowldDRycKgUNSw8MNN/4viBT9usQe6E2iSIs=,tag:JUij1XyxXOs0OF04A+B5Bg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
